# Generated by Django 5.1 on 2025-11-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_empleados', '0002_alter_empleado_options_alter_proyecto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='area',
            field=models.CharField(default='Sin Asignar', max_length=100),
        ),
        migrations.AddField(
            model_name='empleado',
            name='salario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
